export const vendorList = [
  "A.N ELECTRICALS",
  "ABHI TRADERS",
  "B.E.C CONDUITS PVT. LTD",
  "BHAROTI INDUSTRIAL SUPPLIERS",
  "C.P Century Hardware Pvt. Ltd.",
  "Deepak Electronic & Hardware Store",
  "Eagle Sales Corporation",
  "G.S DAGA & CO.",
  "GUJARAT MACHINERY AGENCY",
  "Impex Machinery Corporation",
  "INTEGERATEDELECTRICAL SOLUTIONS",
  "Jai Mata Trader",
  "MAKWELD LLP",
  "MD STEEL WORLD",
  "ORBITAL ENTERPRISES",
  "POLAR",
  "Radhika Enterprises",
  "Radhika Enetrprices",
  "RAMA CABELE HOUSE",
  "RATHORE ELECTRICAL & HARDWARE",
  "SEPL",
  "Shiv Electric & Hardware CO.",
  "Shiv Electric & Trending CO.",
  "Shree Ganesh Enterprises",
  "Shree Nath Enterprices",
  "Shree Siddhivinayak Electric & Hardware",
  "VEER INFOTECH",
  "Veraizen Earthing Pvt. Ltd.",
  "VTR Infotech Pvt. Ltd."
];

export const projectSiteList = [
  "210_TPH_NIRMA",
  "SPCPL_Leh_Airport",
  "TS_JUSCO",
  "INTRC_ATVRM AP 2-P1",
  "JPW_SHALIMAR",
  "LNT_CFCL_KOTA",
  "M3M_CROWN_111",
  "M3M_Merlin_OPUS",
  "TKIL_KRISHNAPATNNAM",
  "TATA_BDD_Chawl",
  "RLDA_DRA_ADI",
  "SPCPL_MUMBAI",
  "DFCC_PROJECT",
  "JORHAT",
  "SILCHAR",
  "JUPALCO NEW CASTER",
  "ELEVATE_GRUGRAM"
];
