export const vendorList = [
  "A.N ELECTRICALS",
  "ABHI TRADERS",
  "B.E.C CONDUITS PVT. LTD",
  "BHAROTI INDUSTRIAL SUPPLIERS",
  "C.P Century Hardware Pvt. Ltd.",
  "Deepak Electronic & Hardware Store",
  "Eagle Sales Corporation",
  "G.S DAGA & CO.",
  "GUJARAT MACHINERY AGENCY",
  "Impex Machinery Corporation",
  "INTEGERATEDELECTRICAL SOLUTIONS",
  "Jai Mata Trader",
  "MAKWELD LLP",
  "MD STEEL WORLD",
  "ORBITAL ENTERPRISES",
  "POLAR",
  "Radhika Enterprises",
  "Radhika Enetrprices",
  "RAMA CABELE HOUSE",
  "RATHORE ELECTRICAL & HARDWARE",
  "SEPL",
  "Shiv Electric & Hardware CO.",
  "Shiv Electric & Trending CO.",
  "Shree Ganesh Enterprises",
  "Shree Nath Enterprices",
  "Shree Siddhivinayak Electric & Hardware",
  "VEER INFOTECH",
  "Veraizen Earthing Pvt. Ltd.",
  "VTR Infotech Pvt. Ltd."
];

export const projectSiteList = [
  "210_TPH_NIRMA",
  "Airport",
  "DFCC-PRYJE-EL-MAINT-TRD",
  "HMM_Bawal",
  "INTRC_ATVRM",
  "JPW_SHALIMAR_Vande_Bharat",
  "L&T_CFCL_TAN_KHURJA",
  "L&T_CFCL_TAN_KOTA",
  "M3M_CROWN_111",
  "M3M_Merlin_67",
  "MHS PACKAGE-BERTH5-AKPL",
  "Ozone BDD_Chawl",
  "RLDA_DRA_ADI Project",
  "SPCPL_ASSAM",
  "SPCPL_Leh",
  "SPCPL_MUMBAI",
  "SPCPL_RAJASTHAN",
  "SPCPL_SONIPAT",
  "TPL_MAC145_Noida",
  "TS_JUSCO"
];
